//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SQLEClient.rc
//
#define IDS_TITLECAPTION                1
#define IDS_FILEVERSION                 2
#define IDS_APPCOPYRIGHT                3
#define IDS_REGISTRYKEY                 4
#define IDS_STRING5                     5
#define IDS_EVENTNAME                   5
#define IDC_HANDCURSOR                  100
#define IDI_MAINICON                    101
#define IDI_MAIN                        101
#define IDD_MAIN                        102
#define IDI_ICON1                       103
#define IDD_SECURITYTAB                 104
#define IDD_ADVANCEDTAB                 105
#define ID_SCHED_ALL                    105
#define IDD_REPLICATION                 106
#define ID_SCHED_NONE                   106
#define IDD_ACCOUNTTAB                  107
#define IDI_ICON2                       109
#define IDI_AVAILFORREP                 109
#define IDI_ICON3                       110
#define IDI_NOTAVAILFORREP              110
#define IDI_ICON4                       111
#define IDI_REPLICATING                 111
#define IDI_REFRESH                     112
#define IDI_ICON5                       113
#define IDR_REPLICATIONLIST             114
#define IDI_ICON6                       115
#define IDI_REPERROR                    115
#define IDI_ICON7                       116
#define IDI_SMCPU                       116
#define IDB_CLOCK                       118
#define IDB_USER                        119
#define IDB_INDEXDB                     120
#define IDI_START                       120
#define IDB_CPUBIG                      121
#define IDI_ICON9                       121
#define IDI_STOP                        121
#define IDB_ENGINE                      122
#define IDB_CLIENTDB                    123
#define IDI_ICON8                       123
#define IDI_SQLSETTING                  123
#define IDI_ACCOUNTS                    124
#define IDB_GENERAL                     125
#define IDI_ADVANCED                    125
#define IDB_PASSWORD                    126
#define IDI_CPUSELECT                   126
#define IDB_SERVER                      127
#define IDI_CRYPTO                      127
#define IDI_GENERAL                     128
#define IDI_SCHEDULE                    129
#define IDI_SECURITY                    130
#define IDR_MAINMENU                    133
#define IDB_SPLASH                      134
#define IDD_SPLASH                      135
#define IDD_SQLTAB                      136
#define IDD_SCHEDTAB                    137
#define TDI_TRAYICON                    138
#define IDD_REPISSUES                   138
#define IDD_STATUSDLG                   141
#define IDD_PENDINGTRANS                142
#define IDD_GENERALTAB                  144
#define IDD_PROCESSORSTAB               145
#define IDD_NETLOGO                     146
#define IDD_SETGUIPWD                   147
#define IDD_ASKPWD                      148
#define IDC_TEXTBOX                     1000
#define ID_DAY_SUN                      1000
#define IDC_NETLINK                     1000
#define IDC_OK                          1001
#define ID_DAY_MON                      1001
#define IDC_CANCEL                      1002
#define ID_DAY_TUE                      1002
#define IDC_STATICTEXT                  1003
#define ID_DAY_WED                      1003
#define IDC_LOGLIST                     1004
#define ID_DAY_THU                      1004
#define IDC_ABOUTICON                   1004
#define IDC_RECVLIST                    1005
#define ID_DAY_FRI                      1005
#define IDC_APPNAME                     1005
#define IDC_DATETIMEPICKER1             1006
#define ID_DAY_SAT                      1006
#define IDC_APPVERSION                  1006
#define IDC_COMPANYPWD                  1007
#define IDC_TALBES                      1007
#define IDC_APPCOPYRIGHT                1007
#define IDC_TCPLOOPDELAY                1008
#define ID_OK                           1008
#define ID_APPLY                        1008
#define IDC_OKBUTTON                    1008
#define IDC_COMPANYNAME                 1009
#define ID_CANCEL                       1009
#define IDC_BUILDTIMEDATE               1009
#define IDC_PORTALSVR                   1010
#define IDC_SERVERADDRESS               1010
#define ID_CKHALL                       1010
#define ID_CHKALL                       1010
#define IDC_PORTALSVRPORT               1011
#define IDC_SERVERPORT                  1011
#define ID_CHKNONE                      1011
#define IDC_STATTEXT                    1011
#define ID_CLOSE                        1012
#define ID_CANCEL2                      1012
#define ID_REPISSUES                    1012
#define IDC_STATPROGRESS                1012
#define ID_PENDINGTRANSACTIONS          1012
#define ID_CLOSE2                       1013
#define ID_REFRESH                      1013
#define IDC_WORKING                     1013
#define IDC_CMDOK                       1013
#define IDC_CHECK1                      1014
#define IDC_CACHELOGFILE                1014
#define IDC_SHOWSPLASHSCREEN            1015
#define IDC_BROWSE_DAT_FOLDER           1016
#define IDC_EDIT1                       1017
#define IDC_SQL_DATA_LOC                1017
#define IDC_AUTHSTRING                  1018
#define IDC_CPUS                        1018
#define IDC_SHOWSPLASHSCREEN2           1018
#define IDC_REPORTNOTRANSACTIONS        1018
#define IDC_BASECOMMKEY                 1019
#define IDC_AUTHKEY                     1019
#define IDC_PRODUCTTEXT                 1019
#define IDC_LOCALCRYPTKEY               1020
#define IDC_VERSIONTEXT                 1020
#define IDC_ADMINPASSWORD1              1021
#define IDC_OSTEXT                      1021
#define IDC_ADMINPASSWORD               1021
#define IDC_ADMINPASSWORD2              1022
#define IDC_MEMORYTEXT                  1022
#define IDC_SPLASHPROGRESS              1023
#define IDC_PROCESORSTEXT               1023
#define IDC_SERVER                      1024
#define IDC_BUILDDATETEXT               1024
#define IDC_PASSWORD                    1024
#define IDC_SQLDRIVER                   1025
#define IDC_CMDCANCEL                   1025
#define IDC_SQLDATABASE                 1026
#define IDC_PASSWORD2                   1026
#define IDC_SQLUSERNAME                 1027
#define IDC_PASSWORD1                   1027
#define IDC_SQLPASSWORD                 1028
#define IDC_CONNECTINTERVAL             1029
#define IDC_VERSIONTAG                  1030
#define IDC_USENTFIBERS                 1032
#define IDC_STATICFRAME                 1038
#define IDC_TOTALCONNECTS               1040
#define IDC_WARNINGS                    1041
#define IDC_ERRORS                      1042
#define ID_HOURS                        2000
#define ID_HOURUD                       2001
#define ID_MINUTES                      3000
#define IDC_THREADBOOST                 3000
#define ID_MINUD                        3001
#define IDC_DROPBADPACKETS              3001
#define IDC_USEPACKEMODE                3002
#define ID_TIMEWINDBEGIN                4000
#define IDC_PROCESSTBOOTS               4000
#define ID_TIMEWINDEND                  4001
#define ID_HELP_ABOUT                   40001
#define ID_SETTINGS_REPLICATION         40002
#define ID_SETTINGS_GENERATEREPLICATIONSQL 40003
#define ID_FILE_CLOSEDLG                40005
#define ID_REPLICATION_SELECTALL        40006
#define ID_REPLICATION_DESELECTALL      40007
#define ID_REPLICATION_SELECTALLOFTHISDATABASE 40008
#define ID_REPLICATION_DESELECTALLOFTHISDATABASE 40009
#define ID_REPLICATION_CANCEL           40010
#define ID_REPLICATION_SELECTALLHIGHLIGHTED 40011
#define ID_CONNECTION_CONNECTNOW        40012
#define ID_REPLICATION_DESELECTALLHIGHLIGHTED 40012
#define ID_CONNECTION_FORCEDISCONNECT   40013
#define ID_SETTINGS_GENERALSETTINGS     40014
#define ID_ADVANCED_PENDING_TRANSACTIONS 40015
#define ID_ADVANCED_DEBUGMODE           40016
#define ID_ADVANCED_OPENCONSOLE         40017
#define ID_ADVANCED_FLUSHVARIABLES      40018
#define ID_SETTINGS_SETPASSWORD         40019
#define ID_HELP_CONTENTS                40020

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         40021
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
