//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SQLEServer.rc
//
#define IDS_TITLECAPTION                1
#define IDS_FILEVERSION                 2
#define IDS_APPCOPYRIGHT                3
#define IDS_REGISTRYKEY                 4
#define IDS_EVENTNAME                   5
#define IDC_HANDCURSOR                  100
#define IDI_MAIN                        101
#define IDD_MAIN                        102
#define IDI_ACCOUNT                     102
#define IDR_SERVERDLGMENU               103
#define IDI_ADVANCED                    103
#define IDD_SECURITYTAB                 104
#define IDI_CPUSELECT                   104
#define IDD_SERVERTAB                   105
#define IDI_CRYPTO                      105
#define IDI_GENERAL                     106
#define IDI_SCHEDULE                    107
#define IDD_CLIENTDBSTAB                108
#define IDI_SECURITY                    108
#define IDI_SERVER                      109
#define IDI_ICON9                       110
#define IDI_SQLSETTING                  110
#define IDI_ICON1                       111
#define IDI_INDEXSQL                    111
#define IDI_PASSWORD                    112
#define IDI_SMCPU                       115
#define IDB_ALERTDLGSKIN                116
#define IDB_SPLASH                      117
#define IDD_ALERT                       119
#define IDI_START                       128
#define IDI_STOP                        129
#define IDD_SPLASH                      135
#define IDD_INDEXDATABASE               136
#define IDD_GENERALTAB                  138
#define IDD_MONITOR                     139
#define IDD_CREATENEWDB                 140
#define IDD_STATUSDLG                   141
#define IDD_SYSSTATS                    142
#define IDD_ADVANCEDTAB                 143
#define IDD_PROCESSORSTAB               144
#define IDD_NETLOGO                     145
#define IDD_ASKPWD                      146
#define IDD_SETGUIPWD                   147
#define IDC_NETLINK                     1000
#define IDC_USAGEGRAPH                  1001
#define IDC_USETRUSTEDCONN              1001
#define IDC_CPUDESCR                    1001
#define IDC_CANCEL                      1002
#define IDC_USESQLTCPIP                 1002
#define IDC_ABOUTICON                   1004
#define IDC_LOGLIST                     1004
#define IDD_NEXTCLIENTID                1005
#define IDC_APPNAME                     1005
#define IDC_LISTENPORT                  1006
#define IDC_APPVERSION                  1006
#define IDC_PREPARE                     1006
#define IDC_MAXCONNECTS                 1007
#define IDC_APPCOPYRIGHT                1007
#define IDC_CREATE                      1007
#define IDC_OKBUTTON                    1008
#define IDC_BUILDTIMEDATE               1009
#define IDC_BACKUPNAME                  1009
#define ID_PAGEFAULTS                   1010
#define ID_MEMORYUSED                   1011
#define IDC_STATTEXT                    1011
#define IDC_DBO                         1011
#define ID_PEAKMEMUSAGE                 1012
#define IDC_STATPROGRESS                1012
#define IDC_PWDWEIGHT                   1012
#define ID_PAGEDPOOLUSAGE               1013
#define IDC_CMDOK                       1013
#define IDC_DATAFILELOC                 1013
#define IDC_ALERTBUTTON1                1013
#define ID_PEAKPAGEDPOOLUSAGE           1014
#define IDC_ALERTBUTTON2                1014
#define IDC_CACHELOGFILE                1014
#define IDC_LOGFILELOC                  1014
#define ID_NPPOOLUSAGE                  1015
#define IDC_COMPRESSMETHOD              1015
#define IDC_RTOFDWI                     1015
#define ID_PEAKNPPOOLUSAGE              1016
#define IDC_AUTORUN                     1016
#define ID_PAGEFILEUSAGE                1017
#define IDC_SHOWSPLASHSCREEN            1017
#define ID_PEAKPAGEFILEUSAGE            1018
#define IDC_CPUS                        1018
#define IDC_BROWSE_DAT_FOLDER           1018
#define IDC_AUTHSTRING                  1019
#define IDC_PRODUCTTEXT                 1019
#define IDC_ALERTONWARNING              1019
#define IDC_AUTHKEY                     1020
#define IDC_VERSIONTEXT                 1020
#define IDC_ALERTSKIN                   1020
#define IDC_ALERTONERRORS               1020
#define IDC_ENCRYPTKEYLEN               1021
#define IDC_OSTEXT                      1021
#define IDC_ALERTCAPTION                1021
#define IDC_SQL_DATA_LOC                1021
#define IDC_ADMINPASSWORD1              1022
#define IDC_MEMORYTEXT                  1022
#define IDC_ALERTMESSAGE                1022
#define IDC_ACKINTERVAL                 1022
#define IDC_HASHTIMEOUT                 1022
#define IDC_SPLASHPROGRESS              1023
#define IDC_ADMINPASSWORD2              1023
#define IDC_PROCESORSTEXT               1023
#define IDC_COMPANYACCT                 1023
#define IDC_ALERTTIMER                  1023
#define IDC_SHOWSPLASHSCREEN2           1023
#define IDC_OFFLINEPROCESSING           1023
#define IDC_BUILDDATETEXT               1024
#define IDC_PASSWORD                    1024
#define IDC_SQL_LOG_LOC                 1024
#define IDC_LOCALCRYPTKEY               1024
#define IDC_CMDCANCEL                   1025
#define IDC_SQLDRIVER                   1025
#define IDC_BROWSE_DAT_FOLDER2          1025
#define IDC_BROWSE_LOG_FOLDER           1025
#define IDC_VERSIONTEXT2                1025
#define IDC_EXPIREDATE                  1025
#define IDC_ADMINPASSWORD               1025
#define IDC_PASSWORD2                   1026
#define IDC_SQLDATABASE                 1026
#define IDC_BROWSEBUTTON                1026
#define IDC_HASHTIMEOUT2                1026
#define IDC_MAXINACTIVITY               1026
#define IDC_PASSWORD1                   1027
#define IDC_SQLUSERNAME                 1027
#define IDC_BROWSE_TEMP                 1027
#define IDC_BROWSE_TEMP_FOLDER          1027
#define IDC_SQLPASSWORD                 1028
#define IDC_TEMPDIR                     1029
#define IDC_SQLPORT                     1029
#define IDC_VERSIONTAG                  1030
#define IDC_SQLPORT2                    1030
#define IDC_SQLCUSTPORT                 1030
#define IDC_SQLSERVER                   1031
#define IDC_USENTFIBERS                 1032
#define IDC_STATICFRAME                 1038
#define IDC_CONNECTIONS                 1039
#define IDC_TOTALCONNECTS               1040
#define IDC_WARNINGS                    1041
#define IDC_ERRORS                      1042
#define IDC_THREADBOOST                 3000
#define IDC_USEPACKEMODE                3002
#define IDC_PROCESSTBOOTS               4000
#define IDC_PROCESSBOOST                4000
#define ID_SERVER_START                 40001
#define ID_SERVER_STOP                  40002
#define ID_SERVER_SETTINGS              40003
#define ID_SETTINGS_SETTINGS            40004
#define ID_SETTINGS_CLEARSTATISTICS     40005
#define ID_SERVER_CLOSE                 40006
#define ID_HELP_ABOUT                   40007
#define ID_SETTINGS_DEBUGMODE           40008
#define ID_SETTINGS_OPENCONSOLE         40009
#define ID_SERVER_SYSTEMSTATISTICS      40010
#define ID_REPLICATION_SETUPNEWDATABASE 40011
#define ID_SETTINGS_SETGUIPWD           40012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
